# Turns a binary file into a C array, the way src/scripts/auto.lua did for
# LOVE's embedded Lua before raw string literals replaced it. The signature
# table (05 の 10.7) is bytes rather than text, so it needs this rather than
# a raw string.
#
# Usage:
#   .\scripts\bin2header.ps1 -In sigs.bin -Out src\lh\Signatures.h -Name lh_signatures

param(
    [Parameter(Mandatory)][string]$In,
    [Parameter(Mandatory)][string]$Out,
    [Parameter(Mandatory)][string]$Name
)

$ErrorActionPreference = "Stop"

$bytes = [System.IO.File]::ReadAllBytes((Resolve-Path $In))

$text = New-Object System.Text.StringBuilder
[void]$text.AppendLine("// Generated by scripts/bin2header.ps1 -- do not edit.")
[void]$text.AppendLine("//")
[void]$text.AppendLine("// 05 の 10.7: the signature table a build without the front end reads in")
[void]$text.AppendLine("// place of parsing each registration's signature text. Written by a full")
[void]$text.AppendLine("// build of this same engine:")
[void]$text.AppendLine("//")
[void]$text.AppendLine("//     lovec.exe --dump-signatures sigs.bin")
[void]$text.AppendLine("//     .\scripts\bin2header.ps1 -In sigs.bin -Out src\lh\Signatures.h -Name $Name")
[void]$text.AppendLine("//")
[void]$text.AppendLine("// Regenerate it whenever a registration changes -- a name the reading")
[void]$text.AppendLine("// program did not register the same way is refused when its turn comes.")
[void]$text.AppendLine()
[void]$text.AppendLine("#pragma once")
[void]$text.AppendLine()
[void]$text.AppendLine("static const unsigned char ${Name}[] = {")

$line = New-Object System.Text.StringBuilder
for ($i = 0; $i -lt $bytes.Length; $i++) {
    if ($line.Length -eq 0) { [void]$line.Append("`t") }
    [void]$line.Append("0x{0:x2}," -f $bytes[$i])
    if ((($i + 1) % 16) -eq 0) {
        [void]$text.AppendLine($line.ToString())
        [void]$line.Clear()
    }
}
if ($line.Length -gt 0) { [void]$text.AppendLine($line.ToString()) }

[void]$text.AppendLine("};")
[void]$text.AppendLine()
[void]$text.AppendLine("static const unsigned long ${Name}_length = $($bytes.Length)UL;")

[System.IO.File]::WriteAllText((Join-Path (Get-Location) $Out), $text.ToString())
Write-Host "wrote $Out ($($bytes.Length) bytes as a C array)"
